#!/bin/bash

#######################################################################
# Copyright 2013 
#    Demand Logic limited <info@demandlogic.co.uk>
#    Nils Toedtmann <nils.toedtmann@demandlogic.co.uk>
#
# This file is part of DemandLogic's ALIX deployment scripts :
#
#    <https://github.com/DemandLogic/dl-alix-voyage>
#
# DemandLogic's ALIX deployment scripts is free software: you can 
# redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
#
# DemandLogic's ALIX deployment scripts is distributed in the hope that
# it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with DemandLogic's ALIX deployment scripts. If not, see 
# <http://www.gnu.org/licenses/>.
#######################################################################


#######################################################################
# This is the chroot part of our script to deploy Voyage Linux 
# onto a compact flash card (CF) for a PC Engine ALIX board
#######################################################################


DEL_PACKAGES="dnsmasq rpcbind hostapd wireless-regdb wpasupplicant"
PRE_PACKAGES="dialog debconf"
PACKAGES="ca-certificates postfix bsd-mailx supervisor munin-node ntpdate procmail openvpn screen ssl-cert telnet vim-nox arping iptraf tcpdump netplug ufw hdparm"
PACKAGES_DLBI="supervisor subversion python python-dev libevent-dev gcc python-pip"
PACKAGES="${PACKAGES} ${PACKAGES_DLBI}"
# open{ssh,ssl,vpn}-blacklist?


# Set simple locale for perl
unset LANGUAGE LC_ALL LC_PAPER LC_ADDRESS LC_MONETARY LC_NUMERIC LC_TELEPHONE LC_IDENTIFICATION LC_MEASUREMENT LC_TIME LC_NAME
export LC_ALL=C LANGUAGE=C LANG=C 

# Tell dpkg to run non-interactively
export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true

apt-get -y remove --purge ${DEL_PACKAGES}
apt-get -y autoremove
apt-get update

# Prepare installation of other packages
apt-get -y install ${PRE_PACKAGES}

HOSTNAME=`cat /etc/hostname`
echo "postfix postfix/mailname          string  ${HOSTNAME}"      | debconf-set-selections
echo "postfix postfix/main_mailer_type  select  No configuration" | debconf-set-selections

echo "tzdata    tzdata/Areas        select  Etc" | debconf-set-selections
echo "tzdata    tzdata/Zones/Etc    select  GMT" | debconf-set-selections

apt-get -y upgrade
apt-get -y install ${PACKAGES}
apt-get clean 


# Set random root password
ROOTPW=`dd if=/dev/urandom bs=1 count=15 2>/dev/null | base64 -w 0 | tr -d '=' | tr '/+' '.-'` 
echo "root:${ROOTPW}" | chpasswd
echo "root password set to '${ROOTPW}'"


# Make sure our ALIX services get started at boot time:
for service in sync_clock sync_future leds reset_button prepare_serial ; do 
    /usr/sbin/update-rc.d $service defaults
done


# We are taking care of the LEDs ourselves:
sed   -e 's/^VOYAGE_LEDS=.*$/VOYAGE_LEDS="NO"/'  -i /etc/default/voyage-util


#Configure netplug to only watch eth0
echo "eth0" > /etc/netplug/netplugd.conf


# Make sure firewall allows ssh and is on after boot
ufw allow ssh
ufw logging off
sed -e 's/^ENABLED=.*$/ENABLED=yes/' -i /etc/ufw/ufw.conf


# This is useless, we have our better sync_time
chmod -x /etc/network/if-up.d/ntpdate


# Clean up
kill `cat /run/dhclient.eth0.pid`
# Stop any services that migh be running after their installation
for s in supervisor munin-node inetutils-syslogd postfix openvpn netplug ; do
    service $s stop
done


# Disable serial console (see https://apps.demandlogic.org/trac/wiki/Serial)
# ... of GRUB:
sed -e 's/^\(serial .*\)$/#\1/'          -i  /boot/grub/menu.lst
sed -e 's/^\(terminal serial .*\)$/#\1/' -i  /boot/grub/menu.lst
# ... of the kernel:
sed -e 's/console=[^ ]*//' -i  /boot/grub/menu.lst
# ... and of the OS: 
sed -e 's/^\(T.* ttyS0 .*\)$/#\1/' -i  /etc/inittab


# Make sure there is at least an empty /etc/default/locale to prevent sshd from whining
touch /etc/default/locale


# Exit the CHROOT
exit 0

